platforms :mswin, :mingw do
  gem 'sys-admin', '1.5.6-x86-mingw32', :path => 'c:\mount\gems'
  gem 'win32-api', '1.4.8-x86-mingw32', :path => 'c:\mount\gems'
  gem 'win32-dir', '0.3.7', :path => 'c:\mount\gems'
  gem 'win32-eventlog', '0.5.3', :path => 'c:\mount\gems'
  gem 'win32-process', '0.6.5', :path => 'c:\mount\gems'
  gem 'win32-security', '0.1.2', :path => 'c:\mount\gems'
  gem 'win32-service', '0.7.2-x86-mingw32', :path => 'c:\mount\gems'
  gem 'win32-taskscheduler', '0.2.2', :path => 'c:\mount\gems'
  gem 'win32console', '1.3.2-x86-mingw32', :path => 'c:\mount\gems'
  gem 'windows-api', '0.4.0', :path => 'c:\mount\gems'
  gem 'windows-pr', '1.2.1', :path => 'c:\mount\gems'
end